export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const USER_LIST = "USER_LIST";
export const USER_REGISTER = "USER_REGISTER";
export const SET_PASSWORD = "SET_PASSWORD";

export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const CHANGE_PROJECT_STATUS = "CHANGE_PROJECT_STATUS";
export const GET_PROJECTS = "GET_PROJECTS";

export const ADD_NEW_QUOTE = "ADD_NEW_QUOTA";
export const UPDATE_QUOTE = "UPDATE_QUOTE";
export const GET_QUOTES = "GET_QUOTES";

export const GET_INVOICES = "GET_INVOICES";
export const UPDATE_INVOICE = "UPDATE_INVOICE";

export const GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS";
